apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - image: ${IMAGE_NAME}:${TAG}
          imagePullPolicy: Always
          name: ${APP_NAME}-nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /status.json
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 30
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: ${APP_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
spec:
  type: LoadBalancer
  selector:
    app: ${APP_NAME}
  ports:
    - name: ${APP_NAME}
      protocol: TCP
      port: 80
      targetPort: 80
