name: Create review app

on:
  pull_request:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Install Dependencies
        run: yarn
      - name: Build App
        run: yarn build
      - name: Delete source maps
        run: find './dist' -name '*.map' -print0 | xargs -0 rm -f
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ~/srv/lllllll/dev/${{ github.head_ref }}"
          rsync -avzP ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/lllllll/dev/${{ github.head_ref }} --delete-after
      - name: Post review app URL
        uses: mshick/add-pr-comment@v1
        with:
          message: Created new review app at ${{ env.REVIEW_APP_URL }}
        env:
          REVIEW_APP_URL: http://${{ github.head_ref }}.dev.lllllll.ru/


